export  const videoInfoDummy = [
{   id:1, 
    createdAt: "2013-07-13T14:35:00Z ", 
    view : 1500,
    creator: [ 
        {name: "dahee", role: "Main Director", imgUrl: "https://velog.velcdn.com/images/beablessing/post/7f30c720-da7c-4a81-9b38-0c84f527a43e/image.png"},
        {name: "virus", role: "Performancer", imgUrl: "https://velog.velcdn.com/images/beablessing/post/be2c8828-ef33-4cfc-9d2d-8e6a6ea553e3/image.png"},
        {name: "lillan", role: "", imgUrl: "https://velog.velcdn.com/images/beablessing/post/ac92cdba-e671-462f-b5ca-a7b09e6baa30/image.png"},
        {name: "phil", role: "Co-Creator", imgUrl: "https://velog.velcdn.com/images/beablessing/post/7f30c720-da7c-4a81-9b38-0c84f527a43e/image.png"},
        {name: "phil", role: "Performancer", imgUrl: "https://velog.velcdn.com/images/beablessing/post/7f30c720-da7c-4a81-9b38-0c84f527a43e/image.png"},
        {name: "dahee", role: "Main Director", imgUrl: "https://velog.velcdn.com/images/beablessing/post/7f30c720-da7c-4a81-9b38-0c84f527a43e/image.png"},
        {name: "virus", role: "Performancer", imgUrl: "https://velog.velcdn.com/images/beablessing/post/be2c8828-ef33-4cfc-9d2d-8e6a6ea553e3/image.png"},
        {name: "lillan", role: "", imgUrl: "https://velog.velcdn.com/images/beablessing/post/ac92cdba-e671-462f-b5ca-a7b09e6baa30/image.png"},
        {name: "phil", role: "Co-Creator", imgUrl: "https://velog.velcdn.com/images/beablessing/post/7f30c720-da7c-4a81-9b38-0c84f527a43e/image.png"},
        {name: "phil", role: "Performancer", imgUrl: "https://velog.velcdn.com/images/beablessing/post/7f30c720-da7c-4a81-9b38-0c84f527a43e/image.png"},
    ],
    title: "WORTH IT", 
    story: `This particular freeze is called a "baby" freeze because it's supposed This particular freeze is called a "baby" freeze because it's supposed This particular freeze is called a "baby" freeze because it's supposed to be one of the easiest ones to learn. It's a move where you hold your body low to the ground, balancing yourself on your hands and head with your feet in the air.    This particular freeze is called a "baby" freeze because it's supposed to be one of the easiest ones to learn. It's a move where you hold your body low to the ground, balancing yourself on your hands and head with your feet in the air.`,
    videoId:"RWHwy8lSxv4", 
    videoThum:"https://images.velog.io/images/beablessing/post/a2014b43-1ce4-44dd-9942-8a6ffac2ea89/Rectangle%2013.png", 
    genre:["Ballet","B-boy","DanceWorkout","K-pop"],
    tags: ["tag1","tag2","tag3","worth"],
},
{   id:2, 
    createdAt: "2020-07-13T14:35:00Z ", 
    view : 200,
    creator: [ 
        {name: "virus", role: "Main Director", imgUrl: "https://velog.velcdn.com/images/beablessing/post/be2c8828-ef33-4cfc-9d2d-8e6a6ea553e3/image.png"},
        {name: "virus", role: "Performancer", imgUrl: "https://velog.velcdn.com/images/beablessing/post/be2c8828-ef33-4cfc-9d2d-8e6a6ea553e3/image.png"},
        {name: "lillan", role: "", imgUrl: "https://velog.velcdn.com/images/beablessing/post/ac92cdba-e671-462f-b5ca-a7b09e6baa30/image.png"},
        {name: "phil", role: "Co-Creator", imgUrl: "https://velog.velcdn.com/images/beablessing/post/7f30c720-da7c-4a81-9b38-0c84f527a43e/image.png"},
        {name: "phil", role: "Performancer", imgUrl: "https://velog.velcdn.com/images/beablessing/post/7f30c720-da7c-4a81-9b38-0c84f527a43e/image.png"},
    ],
    title: "ROYAL FAMILY", 
    story: `This particular freeze is called a "baby" freeze because it's supposed to be one of the easiest ones to learn. It's a move where you hold your body low to the ground, balancing yourself on your hands and head with your feet in the air.    This particular freeze is called a "baby" freeze because it's supposed to be one of the easiest ones to learn. It's a move where you hold your body low to the ground, balancing yourself on your hands and head with your feet in the air.`,
    videoId:"0vspK4Wgl1o", 
    videoThum:"https://images.velog.io/images/beablessing/post/a2014b43-1ce4-44dd-9942-8a6ffac2ea89/Rectangle%2013.png", 
    genre:["크럼프","하우스","DanceWorkout","Etc","크럼프","하우스","DanceWorkout","Etc"],
    tags: ["dance","tag2","tag3","worth"],
},
{   id:3, 
    createdAt: "2020-07-13T14:35:00Z ", 
    view : 200,
    creator: [ 
        {name: "virus", role: "Main Director", imgUrl: "https://velog.velcdn.com/images/beablessing/post/be2c8828-ef33-4cfc-9d2d-8e6a6ea553e3/image.png"},
        {name: "virus", role: "Performancer", imgUrl: "https://velog.velcdn.com/images/beablessing/post/be2c8828-ef33-4cfc-9d2d-8e6a6ea553e3/image.png"},
        {name: "lillan", role: "", imgUrl: "https://velog.velcdn.com/images/beablessing/post/ac92cdba-e671-462f-b5ca-a7b09e6baa30/image.png"},
        {name: "phil", role: "Co-Creator", imgUrl: "https://velog.velcdn.com/images/beablessing/post/7f30c720-da7c-4a81-9b38-0c84f527a43e/image.png"},
        {name: "phil", role: "Performancer", imgUrl: "https://velog.velcdn.com/images/beablessing/post/7f30c720-da7c-4a81-9b38-0c84f527a43e/image.png"},
    ],
    title: "ROYAL FAMILY", 
    story: `This particular freeze is called a "baby" freeze because it's supposed to be one of the easiest ones to learn. It's a move where you hold your body low to the ground, balancing yourself on your hands and head with your feet in the air.    This particular freeze is called a "baby" freeze because it's supposed to be one of the easiest ones to learn. It's a move where you hold your body low to the ground, balancing yourself on your hands and head with your feet in the air.`,
    videoId:"0vspK4Wgl1o", 
    videoThum:"https://images.velog.io/images/beablessing/post/a2014b43-1ce4-44dd-9942-8a6ffac2ea89/Rectangle%2013.png", 
    genre:["크럼프","하우스","DanceWorkout","Etc","크럼프","하우스","DanceWorkout","Etc"],
    tags: ["dance","tag2","tag3","worth"],
},
{   id:4, 
    createdAt: "2020-07-13T14:35:00Z ", 
    view : 200,
    creator: [ 
        {name: "virus", role: "Main Director", imgUrl: "https://velog.velcdn.com/images/beablessing/post/be2c8828-ef33-4cfc-9d2d-8e6a6ea553e3/image.png"},
        {name: "virus", role: "Performancer", imgUrl: "https://velog.velcdn.com/images/beablessing/post/be2c8828-ef33-4cfc-9d2d-8e6a6ea553e3/image.png"},
        {name: "lillan", role: "", imgUrl: "https://velog.velcdn.com/images/beablessing/post/ac92cdba-e671-462f-b5ca-a7b09e6baa30/image.png"},
        {name: "phil", role: "Co-Creator", imgUrl: "https://velog.velcdn.com/images/beablessing/post/7f30c720-da7c-4a81-9b38-0c84f527a43e/image.png"},
        {name: "phil", role: "Performancer", imgUrl: "https://velog.velcdn.com/images/beablessing/post/7f30c720-da7c-4a81-9b38-0c84f527a43e/image.png"},
    ],
    title: "ROYAL FAMILY", 
    story: `This particular freeze is called a "baby" freeze because it's supposed to be one of the easiest ones to learn. It's a move where you hold your body low to the ground, balancing yourself on your hands and head with your feet in the air.    This particular freeze is called a "baby" freeze because it's supposed to be one of the easiest ones to learn. It's a move where you hold your body low to the ground, balancing yourself on your hands and head with your feet in the air.`,
    videoId:"0vspK4Wgl1o", 
    videoThum:"https://images.velog.io/images/beablessing/post/a2014b43-1ce4-44dd-9942-8a6ffac2ea89/Rectangle%2013.png", 
    genre:["크럼프","하우스","DanceWorkout","Etc","크럼프","하우스","DanceWorkout","Etc"],
    tags: ["dance","tag2","tag3","worth"],
},
{   id:5, 
    createdAt: "2020-07-13T14:35:00Z ", 
    view : 200,
    creator: [ 
        {name: "virus", role: "Main Director", imgUrl: "https://velog.velcdn.com/images/beablessing/post/be2c8828-ef33-4cfc-9d2d-8e6a6ea553e3/image.png"},
        {name: "virus", role: "Performancer", imgUrl: "https://velog.velcdn.com/images/beablessing/post/be2c8828-ef33-4cfc-9d2d-8e6a6ea553e3/image.png"},
        {name: "lillan", role: "", imgUrl: "https://velog.velcdn.com/images/beablessing/post/ac92cdba-e671-462f-b5ca-a7b09e6baa30/image.png"},
        {name: "phil", role: "Co-Creator", imgUrl: "https://velog.velcdn.com/images/beablessing/post/7f30c720-da7c-4a81-9b38-0c84f527a43e/image.png"},
        {name: "phil", role: "Performancer", imgUrl: "https://velog.velcdn.com/images/beablessing/post/7f30c720-da7c-4a81-9b38-0c84f527a43e/image.png"},
    ],
    title: "ROYAL FAMILY", 
    story: `This particular freeze is called a "baby" freeze because it's supposed to be one of the easiest ones to learn. It's a move where you hold your body low to the ground, balancing yourself on your hands and head with your feet in the air.    This particular freeze is called a "baby" freeze because it's supposed to be one of the easiest ones to learn. It's a move where you hold your body low to the ground, balancing yourself on your hands and head with your feet in the air.`,
    videoId:"0vspK4Wgl1o", 
    videoThum:"https://images.velog.io/images/beablessing/post/a2014b43-1ce4-44dd-9942-8a6ffac2ea89/Rectangle%2013.png", 
    genre:["크럼프","하우스","DanceWorkout","Etc","크럼프","하우스","DanceWorkout","Etc"],
    tags: ["dance","tag2","tag3","worth"],
},
{   id:6, 
    createdAt: "2020-07-13T14:35:00Z ", 
    view : 200,
    creator: [ 
        {name: "virus", role: "Main Director", imgUrl: "https://velog.velcdn.com/images/beablessing/post/be2c8828-ef33-4cfc-9d2d-8e6a6ea553e3/image.png"},
        {name: "virus", role: "Performancer", imgUrl: "https://velog.velcdn.com/images/beablessing/post/be2c8828-ef33-4cfc-9d2d-8e6a6ea553e3/image.png"},
        {name: "lillan", role: "", imgUrl: "https://velog.velcdn.com/images/beablessing/post/ac92cdba-e671-462f-b5ca-a7b09e6baa30/image.png"},
        {name: "phil", role: "Co-Creator", imgUrl: "https://velog.velcdn.com/images/beablessing/post/7f30c720-da7c-4a81-9b38-0c84f527a43e/image.png"},
        {name: "phil", role: "Performancer", imgUrl: "https://velog.velcdn.com/images/beablessing/post/7f30c720-da7c-4a81-9b38-0c84f527a43e/image.png"},
    ],
    title: "ROYAL FAMILY", 
    story: `This particular freeze is called a "baby" freeze because it's supposed to be one of the easiest ones to learn. It's a move where you hold your body low to the ground, balancing yourself on your hands and head with your feet in the air.    This particular freeze is called a "baby" freeze because it's supposed to be one of the easiest ones to learn. It's a move where you hold your body low to the ground, balancing yourself on your hands and head with your feet in the air.`,
    videoId:"0vspK4Wgl1o", 
    videoThum:"https://images.velog.io/images/beablessing/post/a2014b43-1ce4-44dd-9942-8a6ffac2ea89/Rectangle%2013.png", 
    genre:["크럼프","하우스","DanceWorkout","Etc","크럼프","하우스","DanceWorkout","Etc"],
    tags: ["dance","tag2","tag3","worth"],
},
{   id:8, 
    createdAt: "2020-07-13T14:35:00Z ", 
    view : 200,
    creator: [ 
        {name: "virus", role: "Main Director", imgUrl: "https://velog.velcdn.com/images/beablessing/post/be2c8828-ef33-4cfc-9d2d-8e6a6ea553e3/image.png"},
        {name: "virus", role: "Performancer", imgUrl: "https://velog.velcdn.com/images/beablessing/post/be2c8828-ef33-4cfc-9d2d-8e6a6ea553e3/image.png"},
        {name: "lillan", role: "", imgUrl: "https://velog.velcdn.com/images/beablessing/post/ac92cdba-e671-462f-b5ca-a7b09e6baa30/image.png"},
        {name: "phil", role: "Co-Creator", imgUrl: "https://velog.velcdn.com/images/beablessing/post/7f30c720-da7c-4a81-9b38-0c84f527a43e/image.png"},
        {name: "phil", role: "Performancer", imgUrl: "https://velog.velcdn.com/images/beablessing/post/7f30c720-da7c-4a81-9b38-0c84f527a43e/image.png"},
    ],
    title: "ROYAL FAMILY", 
    story: `This particular freeze is called a "baby" freeze because it's supposed to be one of the easiest ones to learn. It's a move where you hold your body low to the ground, balancing yourself on your hands and head with your feet in the air.    This particular freeze is called a "baby" freeze because it's supposed to be one of the easiest ones to learn. It's a move where you hold your body low to the ground, balancing yourself on your hands and head with your feet in the air.`,
    videoId:"0vspK4Wgl1o", 
    videoThum:"https://images.velog.io/images/beablessing/post/a2014b43-1ce4-44dd-9942-8a6ffac2ea89/Rectangle%2013.png", 
    genre:["크럼프","하우스","DanceWorkout","Etc","크럼프","하우스","DanceWorkout","Etc"],
    tags: ["dance","tag2","tag3","worth"],
},
{   id:8, 
    createdAt: "2020-07-13T14:35:00Z ", 
    view : 200,
    creator: [ 
        {name: "virus", role: "Main Director", imgUrl: "https://velog.velcdn.com/images/beablessing/post/be2c8828-ef33-4cfc-9d2d-8e6a6ea553e3/image.png"},
        {name: "virus", role: "Performancer", imgUrl: "https://velog.velcdn.com/images/beablessing/post/be2c8828-ef33-4cfc-9d2d-8e6a6ea553e3/image.png"},
        {name: "lillan", role: "", imgUrl: "https://velog.velcdn.com/images/beablessing/post/ac92cdba-e671-462f-b5ca-a7b09e6baa30/image.png"},
        {name: "phil", role: "Co-Creator", imgUrl: "https://velog.velcdn.com/images/beablessing/post/7f30c720-da7c-4a81-9b38-0c84f527a43e/image.png"},
        {name: "phil", role: "Performancer", imgUrl: "https://velog.velcdn.com/images/beablessing/post/7f30c720-da7c-4a81-9b38-0c84f527a43e/image.png"},
    ],
    title: "ROYAL FAMILY", 
    story: `This particular freeze is called a "baby" freeze because it's supposed to be one of the easiest ones to learn. It's a move where you hold your body low to the ground, balancing yourself on your hands and head with your feet in the air.    This particular freeze is called a "baby" freeze because it's supposed to be one of the easiest ones to learn. It's a move where you hold your body low to the ground, balancing yourself on your hands and head with your feet in the air.`,
    videoId:"0vspK4Wgl1o", 
    videoThum:"https://images.velog.io/images/beablessing/post/a2014b43-1ce4-44dd-9942-8a6ffac2ea89/Rectangle%2013.png", 
    genre:["크럼프","하우스","DanceWorkout","Etc","크럼프","하우스","DanceWorkout","Etc"],
    tags: ["dance","tag2","tag3","worth"],
},
{   id:9, 
    createdAt: "2020-07-13T14:35:00Z ", 
    view : 200,
    creator: [ 
        {name: "virus", role: "Main Director", imgUrl: "https://velog.velcdn.com/images/beablessing/post/be2c8828-ef33-4cfc-9d2d-8e6a6ea553e3/image.png"},
        {name: "virus", role: "Performancer", imgUrl: "https://velog.velcdn.com/images/beablessing/post/be2c8828-ef33-4cfc-9d2d-8e6a6ea553e3/image.png"},
        {name: "lillan", role: "", imgUrl: "https://velog.velcdn.com/images/beablessing/post/ac92cdba-e671-462f-b5ca-a7b09e6baa30/image.png"},
        {name: "phil", role: "Co-Creator", imgUrl: "https://velog.velcdn.com/images/beablessing/post/7f30c720-da7c-4a81-9b38-0c84f527a43e/image.png"},
        {name: "phil", role: "Performancer", imgUrl: "https://velog.velcdn.com/images/beablessing/post/7f30c720-da7c-4a81-9b38-0c84f527a43e/image.png"},
    ],
    title: "ROYAL FAMILY", 
    story: `This particular freeze is called a "baby" freeze because it's supposed to be one of the easiest ones to learn. It's a move where you hold your body low to the ground, balancing yourself on your hands and head with your feet in the air.    This particular freeze is called a "baby" freeze because it's supposed to be one of the easiest ones to learn. It's a move where you hold your body low to the ground, balancing yourself on your hands and head with your feet in the air.`,
    videoId:"0vspK4Wgl1o", 
    videoThum:"https://images.velog.io/images/beablessing/post/a2014b43-1ce4-44dd-9942-8a6ffac2ea89/Rectangle%2013.png", 
    genre:["크럼프","하우스","DanceWorkout","Etc","크럼프","하우스","DanceWorkout","Etc"],
    tags: ["dance","tag2","tag3","worth"],
},
{   id:10, 
    createdAt: "2020-07-13T14:35:00Z ", 
    view : 200,
    creator: [ 
        {name: "virus", role: "Main Director", imgUrl: "https://velog.velcdn.com/images/beablessing/post/be2c8828-ef33-4cfc-9d2d-8e6a6ea553e3/image.png"},
        {name: "virus", role: "Performancer", imgUrl: "https://velog.velcdn.com/images/beablessing/post/be2c8828-ef33-4cfc-9d2d-8e6a6ea553e3/image.png"},
        {name: "lillan", role: "", imgUrl: "https://velog.velcdn.com/images/beablessing/post/ac92cdba-e671-462f-b5ca-a7b09e6baa30/image.png"},
        {name: "phil", role: "Co-Creator", imgUrl: "https://velog.velcdn.com/images/beablessing/post/7f30c720-da7c-4a81-9b38-0c84f527a43e/image.png"},
        {name: "phil", role: "Performancer", imgUrl: "https://velog.velcdn.com/images/beablessing/post/7f30c720-da7c-4a81-9b38-0c84f527a43e/image.png"},
    ],
    title: "ROYAL FAMILY", 
    story: `This particular freeze is called a "baby" freeze because it's supposed to be one of the easiest ones to learn. It's a move where you hold your body low to the ground, balancing yourself on your hands and head with your feet in the air.    This particular freeze is called a "baby" freeze because it's supposed to be one of the easiest ones to learn. It's a move where you hold your body low to the ground, balancing yourself on your hands and head with your feet in the air.`,
    videoId:"0vspK4Wgl1o", 
    videoThum:"https://images.velog.io/images/beablessing/post/a2014b43-1ce4-44dd-9942-8a6ffac2ea89/Rectangle%2013.png", 
    genre:["크럼프","하우스","DanceWorkout","Etc","크럼프","하우스","DanceWorkout","Etc"],
    tags: ["dance","tag2","tag3","worth"],
},
{   id:11, 
    createdAt: "2020-07-13T14:35:00Z ", 
    view : 200,
    creator: [ 
        {name: "virus", role: "Main Director", imgUrl: "https://velog.velcdn.com/images/beablessing/post/be2c8828-ef33-4cfc-9d2d-8e6a6ea553e3/image.png"},
        {name: "virus", role: "Performancer", imgUrl: "https://velog.velcdn.com/images/beablessing/post/be2c8828-ef33-4cfc-9d2d-8e6a6ea553e3/image.png"},
        {name: "lillan", role: "", imgUrl: "https://velog.velcdn.com/images/beablessing/post/ac92cdba-e671-462f-b5ca-a7b09e6baa30/image.png"},
        {name: "phil", role: "Co-Creator", imgUrl: "https://velog.velcdn.com/images/beablessing/post/7f30c720-da7c-4a81-9b38-0c84f527a43e/image.png"},
        {name: "phil", role: "Performancer", imgUrl: "https://velog.velcdn.com/images/beablessing/post/7f30c720-da7c-4a81-9b38-0c84f527a43e/image.png"},
    ],
    title: "ROYAL FAMILY", 
    story: `This particular freeze is called a "baby" freeze because it's supposed to be one of the easiest ones to learn. It's a move where you hold your body low to the ground, balancing yourself on your hands and head with your feet in the air.    This particular freeze is called a "baby" freeze because it's supposed to be one of the easiest ones to learn. It's a move where you hold your body low to the ground, balancing yourself on your hands and head with your feet in the air.`,
    videoId:"0vspK4Wgl1o", 
    videoThum:"https://images.velog.io/images/beablessing/post/a2014b43-1ce4-44dd-9942-8a6ffac2ea89/Rectangle%2013.png", 
    genre:["크럼프","하우스","DanceWorkout","Etc","크럼프","하우스","DanceWorkout","Etc"],
    tags: ["dance","tag2","tag3","worth"],
},
{   id:12, 
    createdAt: "2020-07-13T14:35:00Z ", 
    view : 200,
    creator: [ 
        {name: "virus", role: "Main Director", imgUrl: "https://velog.velcdn.com/images/beablessing/post/be2c8828-ef33-4cfc-9d2d-8e6a6ea553e3/image.png"},
        {name: "virus", role: "Performancer", imgUrl: "https://velog.velcdn.com/images/beablessing/post/be2c8828-ef33-4cfc-9d2d-8e6a6ea553e3/image.png"},
        {name: "lillan", role: "", imgUrl: "https://velog.velcdn.com/images/beablessing/post/ac92cdba-e671-462f-b5ca-a7b09e6baa30/image.png"},
        {name: "phil", role: "Co-Creator", imgUrl: "https://velog.velcdn.com/images/beablessing/post/7f30c720-da7c-4a81-9b38-0c84f527a43e/image.png"},
        {name: "phil", role: "Performancer", imgUrl: "https://velog.velcdn.com/images/beablessing/post/7f30c720-da7c-4a81-9b38-0c84f527a43e/image.png"},
    ],
    title: "ROYAL FAMILY", 
    story: `This particular freeze is called a "baby" freeze because it's supposed to be one of the easiest ones to learn. It's a move where you hold your body low to the ground, balancing yourself on your hands and head with your feet in the air.    This particular freeze is called a "baby" freeze because it's supposed to be one of the easiest ones to learn. It's a move where you hold your body low to the ground, balancing yourself on your hands and head with your feet in the air.`,
    videoId:"0vspK4Wgl1o", 
    videoThum:"https://images.velog.io/images/beablessing/post/a2014b43-1ce4-44dd-9942-8a6ffac2ea89/Rectangle%2013.png", 
    genre:["크럼프","하우스","DanceWorkout","Etc","크럼프","하우스","DanceWorkout","Etc"],
    tags: ["dance","tag2","tag3","worth"],
},
{   id:13, 
    createdAt: "2020-07-13T14:35:00Z ", 
    view : 200,
    creator: [ 
        {name: "virus", role: "Main Director", imgUrl: "https://velog.velcdn.com/images/beablessing/post/be2c8828-ef33-4cfc-9d2d-8e6a6ea553e3/image.png"},
        {name: "virus", role: "Performancer", imgUrl: "https://velog.velcdn.com/images/beablessing/post/be2c8828-ef33-4cfc-9d2d-8e6a6ea553e3/image.png"},
        {name: "lillan", role: "", imgUrl: "https://velog.velcdn.com/images/beablessing/post/ac92cdba-e671-462f-b5ca-a7b09e6baa30/image.png"},
        {name: "phil", role: "Co-Creator", imgUrl: "https://velog.velcdn.com/images/beablessing/post/7f30c720-da7c-4a81-9b38-0c84f527a43e/image.png"},
        {name: "phil", role: "Performancer", imgUrl: "https://velog.velcdn.com/images/beablessing/post/7f30c720-da7c-4a81-9b38-0c84f527a43e/image.png"},
    ],
    title: "ROYAL FAMILY", 
    story: `This particular freeze is called a "baby" freeze because it's supposed to be one of the easiest ones to learn. It's a move where you hold your body low to the ground, balancing yourself on your hands and head with your feet in the air.    This particular freeze is called a "baby" freeze because it's supposed to be one of the easiest ones to learn. It's a move where you hold your body low to the ground, balancing yourself on your hands and head with your feet in the air.`,
    videoId:"0vspK4Wgl1o", 
    videoThum:"https://images.velog.io/images/beablessing/post/a2014b43-1ce4-44dd-9942-8a6ffac2ea89/Rectangle%2013.png", 
    genre:["크럼프","하우스","DanceWorkout","Etc","크럼프","하우스","DanceWorkout","Etc"],
    tags: ["dance","tag2","tag3","worth"],
},

    // {id:2, createdAt: "2019-09-25", view : 505,creator: "youngin",Title: "WORTH IT",VId:"0vspK4Wgl1o",  Thum:"https://i.ytimg.com/vi/zUDXj8REpAI/hqdefault.jpg", genre:["Popping","힙합","gnere3","gnere4"]},
    // {id:3, createdAt: "2019-010-25", view : 7,creator: "youngSsam",Title: "ROYAL FAMILY",VId:"UAhtJwI33dg",  Thum:"https://i.ytimg.com/vi/Xw6k6Ma0oqo/hqdefault.jpg", genre:["왁킹","하우스","gnere3","K-Pop"]},
    // {id:4, createdAt: "2019-11-25", view : 1,creator: "dahee",Title: "TANK",VId:"UFjpSqlXLdg",  Thum:"https://i.ytimg.com/vi/jRRze9uT3mM/hqdefault.jpg", genre:["Popping","힙합","gnere3","K-Pop"]},
    // {id:5, createdAt: "2019-12-25", view : 2,creator: "lillian",Title: "MY BAG",VId:"RWHwy8lSxv4",  Thum:"https://i.ytimg.com/vi/g-aY10no-NI/hqdefault.jpg", genre:["왁킹","하우스","gnere3","K-Pop"]},
    // {id:6, createdAt: "2020-01-25", view : 5,creator: "lillian",Title: "THE BOX6",VId:"RWHwy8lSxv4",  Thum:"https://images.velog.io/images/beablessing/post/a2014b43-1ce4-44dd-9942-8a6ffac2ea89/Rectangle%2013.png", genre:["Contemporary","힙합","gnere3","K-Pop"]},
    // {id:7, createdAt: "2020-02-25", view : 50,creator: "lillian",Title: "THE BOX7",VId:"RWHwy8lSxv4",  Thum:"https://images.velog.io/images/beablessing/post/a2014b43-1ce4-44dd-9942-8a6ffac2ea89/Rectangle%2013.png", genre:["DanceWorkout","gnere2","gnere3","gnere4"]},
    // {id:8, createdAt: "2020-03-25", view : 40,creator: "lillian",Title: "THE BOX8",VId:"RWHwy8lSxv4",  Thum:"https://images.velog.io/images/beablessing/post/a2014b43-1ce4-44dd-9942-8a6ffac2ea89/Rectangle%2013.png", genre:["Popping","Ballet","gnere3","gnere4"]},
    // {id:9, createdAt: "2020-04-25", view : 1000,creator: "youngSsam",Title: "Dance Title9",VId:"RWHwy8lSxv4",  Thum:"https://images.velog.io/images/beablessing/post/a2014b43-1ce4-44dd-9942-8a6ffac2ea89/Rectangle%2013.png", genre:["크럼프","하우스","gnere3","gnere4"]},
    // {id:10, createdAt: "2020-05-25", view : 75,creator: "daheev",Title: "Dance Title10",VId:"RWHwy8lSxv4",  Thum:"https://images.velog.io/images/beablessing/post/a2014b43-1ce4-44dd-9942-8a6ffac2ea89/Rectangle%2013.png", genre:["Contemporary","gnere2","gnere3","gnere4"]},
    // {id:11, createdAt: "2020-06-25", view : 100,creator: "virus",Title: "Dance Title11",VId:"RWHwy8lSxv4",  Thum:"https://images.velog.io/images/beablessing/post/a2014b43-1ce4-44dd-9942-8a6ffac2ea89/Rectangle%2013.png", genre:["크럼프","gnere2","gnere3","gnere4"]},
    // {id:12, createdAt: "2020-07-25", view : 200,creator: "youngSsam",Title: "Dance Title12",VId:"RWHwy8lSxv4",  Thum:"https://images.velog.io/images/beablessing/post/a2014b43-1ce4-44dd-9942-8a6ffac2ea89/Rectangle%2013.png", genre:["비보잉","힙합","gnere3","gnere4"]},
    // {id:13, createdAt: "2020-08-25", view : 300,creator: "virus",Title: "Dance Title13",VId:"RWHwy8lSxv4",  Thum:"https://images.velog.io/images/beablessing/post/a2014b43-1ce4-44dd-9942-8a6ffac2ea89/Rectangle%2013.png", genre:["Contemporary","gnere2","gnere3","gnere4"]},
    // {id:14, createdAt: "2020-09-25", view : 400,creator: "virus",Title: "Dance Title14",VId:"RWHwy8lSxv4",  Thum:"https://images.velog.io/images/beablessing/post/a2014b43-1ce4-44dd-9942-8a6ffac2ea89/Rectangle%2013.png", genre:["비보잉","gnere2","gnere3","gnere4"]},
];

export const otherVideoInfoDummy = [
    {id:1, Title: "other1", VId:"RWHwy8lSxv4", Thum:"https://images.velog.io/images/beablessing/post/a2014b43-1ce4-44dd-9942-8a6ffac2ea89/Rectangle%2013.png", genre:["gnere1","gnere2","gnere3","gnere4"]},
    {id:2, Title: "other2",VId:"0vspK4Wgl1o",  Thum:"https://i.ytimg.com/vi/zUDXj8REpAI/hqdefault.jpg", genre:["gnere1","gnere2","gnere3","gnere4"]},
    {id:3, Title: "other3",VId:"UAhtJwI33dg",  Thum:"https://i.ytimg.com/vi/Xw6k6Ma0oqo/hqdefault.jpg", genre:["gnere1","gnere2","gnere3","gnere4"]},
    {id:4, Title: "other4",VId:"UFjpSqlXLdg",  Thum:"https://i.ytimg.com/vi/jRRze9uT3mM/hqdefault.jpg", genre:["gnere1","gnere2","gnere3","gnere4"]},
    {id:5, Title: "other5",VId:"RWHwy8lSxv4",  Thum:"https://i.ytimg.com/vi/g-aY10no-NI/hqdefault.jpg", genre:["gnere1","gnere2","gnere3","gnere4"]},
    {id:6, Title: "other6",VId:"RWHwy8lSxv4",  Thum:"https://images.velog.io/images/beablessing/post/a2014b43-1ce4-44dd-9942-8a6ffac2ea89/Rectangle%2013.png", genre:["gnere1","gnere2","gnere3","gnere4"]},
    
];